name: maloc
description: A CLI tool to generate feature packages with Clean Architecture (Melos + BLoC)
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  recase: ^4.1.0

executables:
  maloc:
